export const AVAILABLE_SKILLS = [
  {
    skillCode: "SKL5NLMLP",
    skill: "Java",
    category: "Language",
    aliases: ["java"],
  },
  {
    skillCode: "SKLMVKXX0",
    skill: "Python",
    category: "Language",
    aliases: ["py", "python3"],
  },
  {
    skillCode: "SKLCQASXR",
    skill: "JavaScript",
    category: "Language",
    aliases: ["js", "es6"],
  },
  {
    skillCode: "SKLN2GA8C",
    skill: "TypeScript",
    category: "Language",
    aliases: ["ts"],
  },
  {
    skillCode: "SKLIBE6R6",
    skill: "C++",
    category: "Language",
    aliases: ["cpp"],
  },
  { skillCode: "SKL7VPWTD", skill: "C", category: "Language", aliases: [] },
  {
    skillCode: "SKLQS2HDA",
    skill: "C#",
    category: "Language",
    aliases: ["csharp"],
  },
  {
    skillCode: "SKLOGLNRA",
    skill: "Go",
    category: "Language",
    aliases: ["golang"],
  },
  { skillCode: "SKLQ3LXY0", skill: "Rust", category: "Language", aliases: [] },
  {
    skillCode: "SKLSD20HR",
    skill: "Kotlin",
    category: "Language",
    aliases: [],
  },
  { skillCode: "SKLP0B95E", skill: "Swift", category: "Language", aliases: [] },
  { skillCode: "SKLNXQMAI", skill: "PHP", category: "Language", aliases: [] },
  { skillCode: "SKLYNEGI6", skill: "Dart", category: "Language", aliases: [] },
  {
    skillCode: "SKL8YOBF8",
    skill: "HTML",
    category: "Frontend",
    aliases: ["html5"],
  },
  {
    skillCode: "SKLMTC894",
    skill: "CSS",
    category: "Frontend",
    aliases: ["css3"],
  },
  {
    skillCode: "SKLKOSLNP",
    skill: "React",
    category: "Frontend",
    aliases: ["reactjs", "react.js"],
  },
  {
    skillCode: "SKLYPVYNG",
    skill: "Next.js",
    category: "Frontend",
    aliases: ["next"],
  },
  {
    skillCode: "SKLP0FPG7",
    skill: "Angular",
    category: "Frontend",
    aliases: [],
  },
  {
    skillCode: "SKLI8DD11",
    skill: "Vue.js",
    category: "Frontend",
    aliases: ["vue"],
  },
  {
    skillCode: "SKLUGYZEJ",
    skill: "Tailwind CSS",
    category: "Frontend",
    aliases: ["tailwind"],
  },
  {
    skillCode: "SKLLEZP45",
    skill: "Bootstrap",
    category: "Frontend",
    aliases: [],
  },
  { skillCode: "SKLOEUG8X", skill: "Redux", category: "Frontend", aliases: [] },
  {
    skillCode: "SKL95IR4N",
    skill: "ShadCN",
    category: "Frontend",
    aliases: ["shadcn-ui"],
  },
  {
    skillCode: "SKL9AIRPJ",
    skill: "Node.js",
    category: "Backend",
    aliases: ["node", "nodejs"],
  },
  {
    skillCode: "SKL37UI66",
    skill: "Express.js",
    category: "Backend",
    aliases: ["express"],
  },
  {
    skillCode: "SKLL32R14",
    skill: "Spring Boot",
    category: "Backend",
    aliases: ["spring", "springboot"],
  },
  { skillCode: "SKL09FCWU", skill: "Django", category: "Backend", aliases: [] },
  { skillCode: "SKLSSMODY", skill: "Flask", category: "Backend", aliases: [] },
  {
    skillCode: "SKL4BEAWN",
    skill: "Laravel",
    category: "Backend",
    aliases: [],
  },
  {
    skillCode: "SKLSUPPOE",
    skill: "NestJS",
    category: "Backend",
    aliases: ["nestjs"],
  },
  {
    skillCode: "SKLVYHI74",
    skill: "ASP.NET",
    category: "Backend",
    aliases: ["dotnet"],
  },
  {
    skillCode: "SKL2OY7TI",
    skill: "GraphQL",
    category: "Backend",
    aliases: [],
  },
  {
    skillCode: "SKLRZOKLN",
    skill: "Android Development",
    category: "Mobile",
    aliases: ["android"],
  },
  { skillCode: "SKLQ748QS", skill: "Flutter", category: "Mobile", aliases: [] },
  {
    skillCode: "SKLKGGS15",
    skill: "React Native",
    category: "Mobile",
    aliases: ["react-native"],
  },
  {
    skillCode: "SKLHWO6WU",
    skill: "iOS Development",
    category: "Mobile",
    aliases: ["ios"],
  },
  {
    skillCode: "SKL63YXOP",
    skill: "Kotlin Android",
    category: "Mobile",
    aliases: [],
  },
  {
    skillCode: "SKLXJZU1N",
    skill: "MongoDB",
    category: "Database",
    aliases: ["mongo"],
  },
  {
    skillCode: "SKL0260DV",
    skill: "PostgreSQL",
    category: "Database",
    aliases: ["postgres", "psql"],
  },
  { skillCode: "SKL09GN0C", skill: "MySQL", category: "Database", aliases: [] },
  {
    skillCode: "SKLFQFPET",
    skill: "SQLite",
    category: "Database",
    aliases: [],
  },
  { skillCode: "SKLW19MST", skill: "Redis", category: "Database", aliases: [] },
  {
    skillCode: "SKLQ4Q5OV",
    skill: "Firebase",
    category: "Database",
    aliases: [],
  },
  {
    skillCode: "SKLTETZ5Z",
    skill: "Oracle DB",
    category: "Database",
    aliases: ["oracle"],
  },
  {
    skillCode: "SKLYNEV7F",
    skill: "AWS",
    category: "Cloud & DevOps",
    aliases: ["amazon web services"],
  },
  {
    skillCode: "SKL2DA1NL",
    skill: "Google Cloud",
    category: "Cloud & DevOps",
    aliases: ["gcp"],
  },
  {
    skillCode: "SKL3U8O4K",
    skill: "Microsoft Azure",
    category: "Cloud & DevOps",
    aliases: ["azure"],
  },
  {
    skillCode: "SKLFFGOWO",
    skill: "Docker",
    category: "Cloud & DevOps",
    aliases: [],
  },
  {
    skillCode: "SKLPFM75P",
    skill: "Kubernetes",
    category: "Cloud & DevOps",
    aliases: ["k8s"],
  },
  {
    skillCode: "SKLRF7MGE",
    skill: "CI/CD",
    category: "Cloud & DevOps",
    aliases: [],
  },
  {
    skillCode: "SKL8SI7GF",
    skill: "Jenkins",
    category: "Cloud & DevOps",
    aliases: [],
  },
  {
    skillCode: "SKL1YYOKG",
    skill: "Terraform",
    category: "Cloud & DevOps",
    aliases: [],
  },
  {
    skillCode: "SKLVN8GZP",
    skill: "Linux",
    category: "Cloud & DevOps",
    aliases: [],
  },
  {
    skillCode: "SKLQRWMPG",
    skill: "Machine Learning",
    category: "Data & AI",
    aliases: ["ml"],
  },
  {
    skillCode: "SKLCNPVR2",
    skill: "Deep Learning",
    category: "Data & AI",
    aliases: ["dl"],
  },
  {
    skillCode: "SKLLYPFCK",
    skill: "Data Science",
    category: "Data & AI",
    aliases: [],
  },
  {
    skillCode: "SKL4AW4M2",
    skill: "TensorFlow",
    category: "Data & AI",
    aliases: [],
  },
  {
    skillCode: "SKLHLMYOC",
    skill: "PyTorch",
    category: "Data & AI",
    aliases: [],
  },
  {
    skillCode: "SKLUD8HBF",
    skill: "Pandas",
    category: "Data & AI",
    aliases: [],
  },
  {
    skillCode: "SKLVX5W0R",
    skill: "NumPy",
    category: "Data & AI",
    aliases: [],
  },
  {
    skillCode: "SKLOI2924",
    skill: "Natural Language Processing",
    category: "Data & AI",
    aliases: ["nlp"],
  },
  {
    skillCode: "SKLR1J5R4",
    skill: "Computer Vision",
    category: "Data & AI",
    aliases: ["cv"],
  },
  {
    skillCode: "SKL1HK2CG",
    skill: "Ethical Hacking",
    category: "Cybersecurity",
    aliases: [],
  },
  {
    skillCode: "SKLC5GI5Y",
    skill: "Network Security",
    category: "Cybersecurity",
    aliases: [],
  },
  {
    skillCode: "SKLICHZQ0",
    skill: "Penetration Testing",
    category: "Cybersecurity",
    aliases: ["pentest"],
  },
  {
    skillCode: "SKLCBM1VS",
    skill: "Cryptography",
    category: "Cybersecurity",
    aliases: [],
  },
  {
    skillCode: "SKLFBOVEP",
    skill: "Unit Testing",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKLV9HVC0",
    skill: "Jest",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKLSBK19P",
    skill: "Mocha",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKL86EV60",
    skill: "Selenium",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKLUN5F4E",
    skill: "Cypress",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKLOGWAYB",
    skill: "Postman",
    category: "Testing & QA",
    aliases: [],
  },
  {
    skillCode: "SKLM80RFP",
    skill: "Git",
    category: "Tools",
    aliases: ["github", "gitlab"],
  },
  {
    skillCode: "SKLTMYDOR",
    skill: "VS Code",
    category: "Tools",
    aliases: ["vscode"],
  },
  {
    skillCode: "SKL3VAEPB",
    skill: "IntelliJ IDEA",
    category: "Tools",
    aliases: ["intellij"],
  },
  { skillCode: "SKLWZQTLO", skill: "Jira", category: "Tools", aliases: [] },
  { skillCode: "SKL3SVL2A", skill: "Slack", category: "Tools", aliases: [] },
  { skillCode: "SKLCF7Q7R", skill: "Notion", category: "Tools", aliases: [] },
  { skillCode: "SKLT9YBZ1", skill: "Figma", category: "Design", aliases: [] },
  {
    skillCode: "SKLWRPOMC",
    skill: "UI Design",
    category: "Design",
    aliases: [],
  },
  {
    skillCode: "SKLEN3PL7",
    skill: "UX Design",
    category: "Design",
    aliases: [],
  },
  {
    skillCode: "SKLVPXI21",
    skill: "Adobe XD",
    category: "Design",
    aliases: [],
  },
  {
    skillCode: "SKLF4M0NB",
    skill: "Communication",
    category: "Soft Skill",
    aliases: [],
  },
  {
    skillCode: "SKLF0DVDS",
    skill: "Leadership",
    category: "Soft Skill",
    aliases: [],
  },
  {
    skillCode: "SKL4J2U2R",
    skill: "Problem Solving",
    category: "Soft Skill",
    aliases: [],
  },
  {
    skillCode: "SKLSHIPLH",
    skill: "Teamwork",
    category: "Soft Skill",
    aliases: [],
  },
  {
    skillCode: "SKLGI3Z9K",
    skill: "Time Management",
    category: "Soft Skill",
    aliases: [],
  },
];

export const FALLBACK_SKILL_OPTIONS = AVAILABLE_SKILLS.map((skill) => ({
  skillCode: skill.skillCode,
  name: skill.skill,
  category: skill.category,
  aliases: skill.aliases || [],
}));